/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package manage_hotel;

import Dao.CheckOutDao;
import Entity.CheckOut;
import Entity.ManageRoom;
import java.awt.HeadlessException;
import java.beans.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class CheckOUt extends javax.swing.JDialog {
CheckOutDao dao = new CheckOutDao();
    /**
     * Creates new form CheckOUt
     */
    public CheckOUt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.fillTable();
        setLocationRelativeTo(null);
         SimpleDateFormat  dat=new SimpleDateFormat("yyyy-MM-dd ");
         Date d=new Date();
         txtOut.setText(dat.format(d));
    }
void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblCO.getModel();
        
        model.setRowCount(0);
        try {
            List<CheckOut> list = dao.selectAll();
            for ( CheckOut cd : list) {
                Object[] row = {
                    cd.getNamess(),
                    cd.getIdCus(),
//                    cd.getPhone(),
//                    cd.getId(),
                    cd.getRoomNumber(),
                    cd.getBedType(),
                    cd.getRoomType(),
//                    cd.getJoindate(),
//                    cd.getBillid(),
//                    cd.getDayx(),
                    cd.getPrice(),
//                        cd.getAmount()
                };
                model.addRow(row);
            }
        } 
        catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
int index=0;
void edit() {
        String RoomNumber = (String) tblCO.getValueAt(index, 0);
        CheckOut co = dao.selectCO(RoomNumber);
       this.setForm(co);
        
//        tabs.setSelectedIndex(0);
    }
    private void setForm(CheckOut co){
        txtCN.setText(co.getNames());
//       cboRoom.setSelectedItem(tblRoom.getValueAt(index, 1));
    txtPN.setText(co.getPhone());
       txtID.setText(co.getId());
  
    txtCD.setText(co.getJoindate());
    }
    void reset(){
//    txtAdress.setText("");
    txtAmout.setText("");
    txtCD.setText("");
    txtCN.setText("");
    txtDay.setText("");
//    txtNation.setText("")
txtNhanVien.setText("");
    txtID.setText("");
    txtPN.setText("");
    txtPrice.setText("");
    txtRoomNumber.setText("");
    cbAir.setSelected(false);
    cbLau.setSelected(false);
    cbRoomService.setSelected(false);
    cbWa.setSelected(false);
//    cbAir.setText("");
//    cbLau.setText("");
//    cbRoomService.setText("");
//    cbWa.setText("");
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAmout = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtOut = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbRoomService = new javax.swing.JCheckBox();
        cbLau = new javax.swing.JCheckBox();
        cbAir = new javax.swing.JCheckBox();
        cbWa = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        txtPriceService = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCO = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtCD = new javax.swing.JTextField();
        btnCO = new javax.swing.JButton();
        txtTotalSum = new javax.swing.JTextField();

        jTextField10.setText("jTextField10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Check out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 17, -1, -1));
        getContentPane().add(txtRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 48, 81, 31));

        btnSearch.setText("Search");
        btnSearch.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnSearchAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                btnSearchAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                btnSearchAncestorRemoved(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 48, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 97, -1, -1));

        txtCN.setBackground(new java.awt.Color(204, 204, 204));
        txtCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCN.setEnabled(false);
        getContentPane().add(txtCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 125, 113, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 97, -1, -1));

        txtPN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPN.setEnabled(false);
        getContentPane().add(txtPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 125, 114, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 97, -1, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtID.setEnabled(false);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 125, 118, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Price Per Day");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 182, -1, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPrice.setEnabled(false);
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 216, 112, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Number Of Days ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 182, -1, -1));

        txtDay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDay.setEnabled(false);
        getContentPane().add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 216, 114, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Total Day Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 182, -1, -1));

        txtAmout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAmout.setEnabled(false);
        getContentPane().add(txtAmout, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 216, 118, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Check In Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 256, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Check Out");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 256, -1, -1));

        txtOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtOut.setEnabled(false);
        getContentPane().add(txtOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 114, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 97, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        cbRoomService.setText("Room Service (50)");
        cbRoomService.setContentAreaFilled(false);

        cbLau.setText("Laundry Service (30)");

        cbAir.setText("Airpot Shuttle (10)");

        cbWa.setText("Wake-Up Service (5)");

        jLabel15.setText("SERVICES");

        txtPriceService.setEditable(false);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPriceService, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbAir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbRoomService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbLau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbWa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRoomService)
                    .addComponent(cbLau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAir)
                    .addComponent(cbWa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPriceService)
                        .addGap(5, 5, 5)))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 69, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Staff");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 256, -1, -1));

        txtNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNhanVien.setEnabled(false);
        getContentPane().add(txtNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 290, 118, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Total Amount");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 335, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Room Number");

        tblCO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Staff", "Customer ID", "Room Number", "Room Type", "Bed Type", "Price"
            }
        ));
        tblCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCO);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtCD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCD.setEnabled(false);

        btnCO.setText("Check out Now ");
        btnCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCOActionPerformed(evt);
            }
        });

        txtTotalSum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotalSum.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCD, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTotalSum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnCO)
                                .addGap(71, 71, 71)
                                .addComponent(jButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(604, 604, 604)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(txtCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnCO)
                    .addComponent(txtTotalSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst = null;
        Statement st = null;
        ResultSet rs = null;
        double totalServicePrice=0;
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost;database=HotelSN","sa","songlong");
            pst = con.prepareStatement("select nameCus,phone,CCCD,joindate,Price,RoomService,LaundryService,Airpot,Wakeup,names from Customerxy where RoomNumber=? AND status1=?");
            pst.setString(1, txtRoomNumber.getText().trim());
            pst.setString(2, "Booking");
            rs = pst.executeQuery();
            if (rs.next()) {
                txtCN.setText(rs.getString("nameCus"));
                txtPN.setText(rs.getString("phone"));
                txtID.setText(rs.getString("CCCD"));
                txtCD.setText(rs.getString("joindate"));
                txtPrice.setText(rs.getString("Price"));
                txtNhanVien.setText(rs.getString("names"));
                cbRoomService.setSelected(rs.getBoolean("RoomService"));
                cbLau.setSelected(rs.getBoolean("LaundryService"));
                cbAir.setSelected(rs.getBoolean("Airpot"));
                cbWa.setSelected(rs.getBoolean("Wakeup"));

              
           
             

                

            }
             if (cbRoomService.isSelected()) {
            totalServicePrice += 50;
        }

        if (cbLau.isSelected()) {
            totalServicePrice += 30;
        }

        if (cbAir.isSelected()) {
            totalServicePrice += 10;
        }

        if (cbWa.isSelected()) {
            totalServicePrice += 5;
        }

        txtPriceService.setText(String.valueOf(totalServicePrice));
            ZoneId z=ZoneId.of("Asia/Colombo");
            LocalDate todays=LocalDate.now(z);
            String s1=todays.toString();
            SimpleDateFormat sim=new SimpleDateFormat("yyyy-MM-dd");
            String f1=rs.getString("joindate");
            String f2=s1;
            try{
                Date d1=sim.parse(f1);
                Date d2=sim.parse(f2);
                long diff=d2.getTime()-d1.getTime();
                int days=(int)(diff/(1000*24*60*60));
                if(days==0)
                   txtAmout.setText("1");
                else
                    txtDay.setText(String.valueOf(days));
                double p=Double.parseDouble(rs.getString("Price"));
                double pri=days*p;
                if(days==0)
                    txtAmout.setText(String.valueOf(p));
                else
                    txtAmout.setText(String.valueOf(pri));
               
    
       String txtAmoutValue = txtAmout.getText().trim();
double amout = Double.parseDouble(txtAmoutValue);

String txtPriceServiceValue = txtPriceService.getText().trim();
double priceService = Double.parseDouble(txtPriceServiceValue);

double sum = amout + priceService;

txtTotalSum.setText(String.valueOf(sum));
            }catch(Exception e){
            }  
        } catch (ClassNotFoundException | SQLException ex) {
//           txtDay.setText("");
//            txtAmout.setText("");
//             JOptionPane.showMessageDialog(this,"Record Not Found.");
            JOptionPane.showMessageDialog(this,"Not found");
            reset();
            //Logger.getLogger(CustomerCheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCOActionPerformed
        // TODO add your handling code here:
         if (txtCN.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Room Number And Search it,Then Check Out Customer");
        } else {
            try {
                PreparedStatement pst = null;
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                java.sql.Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost;database=HotelSN;","sa","songlong");
                pst = con.prepareStatement("update Customerxy set status1=? where RoomNumber=?");
                pst.setString(1, "check out");
                pst.setString(2, txtRoomNumber.getText());
                pst.executeUpdate();
                pst = con.prepareStatement("update Customerxy set amount=?,amountService=?, amountSum=?,outdate=?,dayx=? where RoomNumber=? AND joindate=?");
                pst.setString(1, txtAmout.getText());
                pst.setString(2, txtPriceService.getText());
                pst.setString(3, txtTotalSum.getText());
                pst.setString(4, txtOut.getText());
                pst.setString(5, txtDay.getText());
                pst.setString(6, txtRoomNumber.getText());
                pst.setString(7, txtCD.getText());
                pst.executeUpdate();
                pst = con.prepareStatement("update roomxy set status1=? where RoomNumber=?");
                pst.setString(1, "Not Booking");
                pst.setString(2, txtRoomNumber.getText());
                pst.executeUpdate();
                //JOptionPane.showMessageDialog(this,"Check Out Successfully\n Goto to Cutomer Bill Details menu and Print Bill");
                int yes=JOptionPane.showConfirmDialog(this,"Check out Successfully.\nDo you want to see & print bill?","Check outed",JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION==yes){
                    this.dispose();
                    new BillDetails(new javax.swing.JFrame(), true).setVisible(true);
                    
                }
                else{
                    edit();
//                txtname.setText("");
//                txtemail.setText("");
//                txtmobile.setText("");
//                txtdate.setText("");
//                txtprice.setText("");
//                txtdays.setText("");
//                txtamount.setText("");
//                txtroomnumber.setText("");
                        }
            } catch (ClassNotFoundException | SQLException e) {
            }

        }
    }//GEN-LAST:event_btnCOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost;database=HotelSN;","sa","songlong");
            pst=con.prepareStatement("update Customerxy set RoomService=?,LaundryService=?,Airpot=?,Wakeup=? where RoomNumber=?");
             boolean airValue = cbAir.isSelected();
            pst.setBoolean(3, airValue);
//            pst.setString(12,cbAir.getText());
            boolean airLau = cbLau.isSelected();
            pst.setBoolean(2, airLau);
//            pst.setString(13,cbLau.getText());
            boolean airRoom = cbRoomService.isSelected();
            pst.setBoolean(1, airRoom);
//            pst.setString(14,cbRoomService.getText());
            boolean airWa = cbWa.isSelected();
            pst.setBoolean(4, airWa);
            pst.setString(5,txtRoomNumber.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully");
            btnSearchActionPerformed(evt);
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblCOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCOMouseClicked
        // TODO add your handling code here:
        //         this.index= tblCO.getSelectedRow();
        //            this.edit();
    }//GEN-LAST:event_tblCOMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSearchAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnSearchAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAncestorAdded

    private void btnSearchAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnSearchAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAncestorMoved

    private void btnSearchAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnSearchAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOUt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOUt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOUt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOUt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckOUt dialog = new CheckOUt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCO;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox cbAir;
    private javax.swing.JCheckBox cbLau;
    private javax.swing.JCheckBox cbRoomService;
    private javax.swing.JCheckBox cbWa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTable tblCO;
    private javax.swing.JTextField txtAmout;
    private javax.swing.JTextField txtCD;
    private javax.swing.JTextField txtCN;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtOut;
    private javax.swing.JTextField txtPN;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPriceService;
    private javax.swing.JTextField txtRoomNumber;
    private javax.swing.JTextField txtTotalSum;
    // End of variables declaration//GEN-END:variables
}
