/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package manage_hotel;
import Entity.ManageRoom;
import Dao.ManageRoomDao;

import static org.junit.Assert.*;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.junit.Before;
import org.junit.Test;

/**
 *
 * @author Admin
 */
public class JManageRoom extends javax.swing.JDialog {
ManageRoomDao dao = new ManageRoomDao();
String connectionUrl = "jdbc:sqlserver://localhost;database=HotelSN;";
    String username = "sa";
    String password = "songlong";
    /**
     * Creates new form ManageRoom
     */
      int index=0;
    public JManageRoom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      
        this.fillTable();
//        s();
//showdetail();
//        load_date();
        setLocationRelativeTo(null);
    }
    
void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblRoom.getModel();
        
        model.setRowCount(0);
        try {
            List<ManageRoom> list = dao.selectAll();
            for (ManageRoom cd : list) {
                Object[] row = {
                    cd.getRoomNumber(),
                    cd.getRoomType(),
                    cd.getBedType(),
                    cd.getPrice(),
                    cd.getStatus1()
                };
                model.addRow(row);
            }
        } 
        catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
void edit() {
        String RoomNumber = (String) tblRoom.getValueAt(index, 0);
        ManageRoom mr = dao.selectRoom(RoomNumber);
       this.setForm(mr);
        
//        tabs.setSelectedIndex(0);
    }
void reset(){
    txtPrice.setText("");
    txtRoomNumber.setText("");
    cboBed.setSelectedItem("");
    cboRoom.setSelectedItem("");
    cboSta.setSelectedItem("");
    
}
    private void setForm(ManageRoom mr){
        txtRoomNumber.setText(mr.getRoomNumber());
//       cboRoom.setSelectedItem(tblRoom.getValueAt(index, 1));
cboRoom.setSelectedItem(mr.getRoomType());
        cboBed.setSelectedItem(mr.getBedType());
    txtPrice.setText(mr.getPrice());
    txtST.setText(mr.getStatus1());
   

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtST = new javax.swing.JTextField();
        cboSta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboRoom = new javax.swing.JComboBox<>();
        cboBed = new javax.swing.JComboBox<>();
        txtBook = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRoom = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        txtST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTActionPerformed(evt);
            }
        });

        cboSta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Booked", "Booking", " " }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 67, -1, -1));

        txtRoomNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRoomNumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, 97, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 67, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Bed Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 67, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 67, -1, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 101, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 67, -1, -1));

        cboRoom.setBackground(new java.awt.Color(153, 255, 204));
        cboRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Room", "Double Room", "Luxury Room", "VIP Room", "Twin Room." }));
        getContentPane().add(cboRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 101, -1, -1));

        cboBed.setBackground(new java.awt.Color(102, 255, 204));
        cboBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "King-Size Bed", "Queen-Size Bed", "Grand-King Size Bed", "Twin-Bed" }));
        getContentPane().add(cboBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 101, -1, -1));

        txtBook.setEditable(false);
        txtBook.setText("Not Booking");
        getContentPane().add(txtBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 101, 85, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(204, 204, 255));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        tblRoom.setBackground(new java.awt.Color(204, 255, 204));
        tblRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RoomNumber", "RoomType", "BedType", "Price", "Status"
            }
        ));
        tblRoom.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblRoom.setShowGrid(true);
        tblRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblRoom);
        if (tblRoom.getColumnModel().getColumnCount() > 0) {
            tblRoom.getColumnModel().getColumn(0).setResizable(false);
            tblRoom.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblRoom.getColumnModel().getColumn(3).setResizable(false);
            tblRoom.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ManageRoom");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update))
                        .addGap(1, 1, 1)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(320, 320, 320))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(Update))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomMouseClicked
        // TODO add your handling code here:
        this.index= tblRoom.getSelectedRow();
            this.edit();
    }//GEN-LAST:event_tblRoomMouseClicked
@Test
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Price = txtPrice.getText().trim();
String roomNumber = txtRoomNumber.getText().trim();
int roomNumberValue = Integer.parseInt(roomNumber);
int PriceValue = Integer.parseInt(Price);
        if(txtRoomNumber.getText().equals("")){
      JOptionPane.showMessageDialog(this, "All Field is Requied");
      txtRoomNumber.requestFocus();
    }
        else if(roomNumberValue<0 || roomNumberValue >100){
            JOptionPane.showMessageDialog(this, "Too much");
        }
    else if(Price.equals("")){
       JOptionPane.showMessageDialog(this, "All Field is Requied");
       txtPrice.requestFocus();
    }   
    else if(PriceValue < 0 || PriceValue > 1000){
        JOptionPane.showMessageDialog(this, "Too much");
    }
   
    else{           // TODO add your handling code here:
         try {
            PreparedStatement pst;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost;database=HotelSN;","sa","songlong");
            pst=con.prepareStatement("insert into roomxy(RoomNumber,RoomType,BedType,Price,status1)values(?,?,?,?,?)");
            pst.setString(1, txtRoomNumber.getText());
            pst.setString(2, (String)cboRoom.getSelectedItem());
            pst.setString(3, (String)cboBed.getSelectedItem());
            pst.setString(4, txtPrice.getText());
//            pst.setString(4, (String)cbArea.getSelectedItem());
            pst.setString(5, txtBook.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Room Alloted");
            reset();
            fillTable();
            }catch(HeadlessException | ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this, "Duplicate RoomNumber");
            }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSTActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        // TODO add your handling code here:
  char c =evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtRoomNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomNumberKeyTyped
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtRoomNumberKeyTyped
@Test
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst;
            ResultSet rs;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost;database=HotelSN;","sa","songlong");
            pst=con.prepareStatement("delete from roomxy where RoomNumber=?");
            pst.setString(1, txtRoomNumber.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully");
            fillTable();
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
             JOptionPane.showMessageDialog(this, "Renting");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

@Test
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:

try {
    PreparedStatement pst;
    ResultSet rs;
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    java.sql.Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost;database=HotelSN;","sa","songlong");
    pst=con.prepareStatement("UPDATE roomxy SET RoomType=?, BedType=?, Price=? WHERE RoomNumber=? AND status1='Not Booking'");
    pst.setString(1, (String)cboRoom.getSelectedItem());
    pst.setString(2, (String)cboBed.getSelectedItem());
    pst.setString(3, txtPrice.getText());
    pst.setString(4, txtRoomNumber.getText());
    int affectedRows = pst.executeUpdate();
    if (affectedRows > 0) {
        JOptionPane.showMessageDialog(this, "Successfully");
        fillTable();
    } else {
        JOptionPane.showMessageDialog(this, "Renting that can not update");
        fillTable();
    }
} catch(HeadlessException | ClassNotFoundException | SQLException e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JManageRoom dialog = new JManageRoom(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> cboBed;
    private javax.swing.JComboBox<String> cboRoom;
    private javax.swing.JComboBox<String> cboSta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblRoom;
    private javax.swing.JTextField txtBook;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNumber;
    private javax.swing.JTextField txtST;
    // End of variables declaration//GEN-END:variables
}
